language: java
jdk:
  - openjdk11

before_install:
  - pip install --user codecov
after_success:
#  - bash <(curl -s https://codecov.io/bash)
  -codecov --file build/reports/jacoco/test/jacocoTestReport.xml --disable search
