version: '2'
services:
  postgres:
    image: library/postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: padles
      POSTGRES_PASSWORD: local
      POSTGRES_USER: padles_admin
  redis:
    image: library/redis:6.0.8-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
